// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using xmlParserASP.Presistant;

#nullable disable

namespace xmlParserASP.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20230703204713_Cat")]
    partial class Cat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("xmlParserASP.Models.CategoryRelation", b =>
                {
                    b.Property<int>("MyCatId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierCatId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.HasKey("MyCatId", "SupplierCatId", "SupplierId", "LanguageId");

                    b.ToTable("CategoriesRelation");
                });

            modelBuilder.Entity("xmlParserASP.Models.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("MyAttributeAttrId")
                        .HasColumnType("int");

                    b.HasKey("LanguageId");

                    b.HasIndex("MyAttributeAttrId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("xmlParserASP.Models.MyAttribute", b =>
                {
                    b.Property<int>("AttrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Attr_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ParentAttrId")
                        .HasColumnType("int");

                    b.Property<int>("SuppAttrIdEqualsOurAttr")
                        .HasColumnType("int");

                    b.Property<int>("SuppAttrNameEqualsOurAttr")
                        .HasColumnType("int");

                    b.HasKey("AttrId");

                    b.ToTable("MyAttributes");
                });

            modelBuilder.Entity("xmlParserASP.Models.MyCategory", b =>
                {
                    b.Property<int>("CatId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Cat_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ParentCatId")
                        .HasColumnType("int");

                    b.HasKey("CatId", "LanguageId");

                    b.ToTable("MyCategories");
                });

            modelBuilder.Entity("xmlParserASP.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("MyAttributeAttrId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierName")
                        .HasColumnType("int");

                    b.HasKey("SupplierId");

                    b.HasIndex("MyAttributeAttrId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("xmlParserASP.Models.SupplierCategory", b =>
                {
                    b.Property<int>("CatId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Cat_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ParentCatId")
                        .HasColumnType("int");

                    b.HasKey("CatId", "SupplierId", "LanguageId");

                    b.ToTable("SupplierCategories");
                });

            modelBuilder.Entity("xmlParserASP.Models.Language", b =>
                {
                    b.HasOne("xmlParserASP.Models.MyAttribute", null)
                        .WithMany("Languages")
                        .HasForeignKey("MyAttributeAttrId");
                });

            modelBuilder.Entity("xmlParserASP.Models.Supplier", b =>
                {
                    b.HasOne("xmlParserASP.Models.MyAttribute", null)
                        .WithMany("Suppliers")
                        .HasForeignKey("MyAttributeAttrId");
                });

            modelBuilder.Entity("xmlParserASP.Models.MyAttribute", b =>
                {
                    b.Navigation("Languages");

                    b.Navigation("Suppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
