// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using xmlParserASP.Presistant;

#nullable disable

namespace xmlParserASP.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20230704200732_Cat")]
    partial class Cat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("xmlParserASP.Models.AttributeRelation", b =>
                {
                    b.Property<int>("MyAttrId")
                        .HasColumnType("int");

                    b.Property<int>("SupAttrId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.HasKey("MyAttrId", "SupAttrId", "SupplierId", "LanguageId");

                    b.ToTable("AttributesRelation");
                });

            modelBuilder.Entity("xmlParserASP.Models.CategoryRelation", b =>
                {
                    b.Property<int>("MyCatId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierCatId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.HasKey("MyCatId", "SupplierCatId", "SupplierId", "LanguageId");

                    b.ToTable("CategoriesRelation");
                });

            modelBuilder.Entity("xmlParserASP.Models.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("xmlParserASP.Models.MyAttribute", b =>
                {
                    b.Property<int>("MyAttrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("MyAttrName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MyAttrId");

                    b.ToTable("MyAttributes");
                });

            modelBuilder.Entity("xmlParserASP.Models.MyCategory", b =>
                {
                    b.Property<int>("MyCatId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("MyCatName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MyParentCatId")
                        .HasColumnType("int");

                    b.HasKey("MyCatId", "LanguageId");

                    b.ToTable("MyCategories");
                });

            modelBuilder.Entity("xmlParserASP.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("MyCatId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("date_added")
                        .HasColumnType("longtext");

                    b.Property<string>("date_available")
                        .HasColumnType("longtext");

                    b.Property<string>("date_modified")
                        .HasColumnType("longtext");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("image_name")
                        .HasColumnType("longtext");

                    b.Property<string>("manufacturer")
                        .HasColumnType("longtext");

                    b.Property<int?>("model")
                        .HasColumnType("int");

                    b.Property<int?>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("seo_keyword")
                        .HasColumnType("longtext");

                    b.Property<int?>("sku")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.HasKey("ProductId", "LanguageId", "MyCatId", "SupplierId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("xmlParserASP.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("SupplierName")
                        .HasColumnType("int");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("xmlParserASP.Models.SupplierAttribute", b =>
                {
                    b.Property<int>("SupAttrId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("SupAttrName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SupAttrId", "SupplierId", "LanguageId");

                    b.ToTable("SupplierAttributes");
                });

            modelBuilder.Entity("xmlParserASP.Models.SupplierCategory", b =>
                {
                    b.Property<int>("SupplierCatId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Cat_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ParentSupCatId")
                        .HasColumnType("int");

                    b.HasKey("SupplierCatId", "SupplierId", "LanguageId");

                    b.ToTable("SupplierCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
